// <auto-generated />
namespace ScalabiltyHomework.Data.Migrations_Read
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialRead : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialRead));
        
        string IMigrationMetadata.Id
        {
            get { return "201601172338212_InitialRead"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
